spring:
    datasource:
        url: jdbc:sqlserver://azureems-server.database.windows.net:1433;databaseName=emsdatabase;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
        username: emsroot
        password: Amaresh@55
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.SQLServer2012Dialect


server:
    port: 9191

springfox:
    swagger:
        enabled: true



